FROM python:3.12-slim
WORKDIR /course
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY shared ./shared
COPY 10_async-task-and-redis-worker ./10_async-task-and-redis-worker
ENV PYTHONPATH=/course
CMD ["python", "10_async-task-and-redis-worker/worker.py"]
